- hosts: all
  become: true

  tasks:
    - name: Install the unzip package
      apt:
        name: unzip
        state: present

    - name: Download and extract Consul in /bin
      unarchive:
        src: https://releases.hashicorp.com/consul/1.0.2/consul_1.0.2_linux_amd64.zip?_ga=2.215178783.987358393.1516195766-1863139472.1516195766
        dest: /bin/
        remote_src: yes
