- hosts: all
  become: true

  tasks:
    - name: Install the unzip package
      apt:
        name: unzip
        state: present

    - name: Download and extract Consul in /bin
      unarchive:
        src: https://releases.hashicorp.com/consul/1.0.3/consul_1.0.3_linux_amd64.zip?_ga=2.181892327.139238098.1517859792-1863139472.1516195766
        dest: /bin/
        remote_src: yes

    - name: Make default config directory
      command: sudo mkdir /etc/consul.d

    - name: Launch Consul.
      shell: nohup /bin/consul agent -dev </dev/null >/dev/null 2>&1 &
