apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-11-07T13:05:33Z
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.18.1
    component: controller
    heritage: Tiller
    release: nginx-ingress
  name: nginx-ingress-controller
  namespace: default
  resourceVersion: "236122"
  selfLink: /api/v1/namespaces/default/services/nginx-ingress-controller
  uid: cf8d2189-e28d-11e8-92cc-42010a840158
spec:
  clusterIP: 10.0.7.22
  externalTrafficPolicy: Cluster
  loadBalancerIP: 35.195.57.244
  ports:
  - name: http
    nodePort: 30923
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31529
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-ingress
    component: controller
    release: nginx-ingress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.195.57.244
