apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-11-07T13:05:33Z
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.18.1
    component: default-backend
    heritage: Tiller
    release: nginx-ingress
  name: nginx-ingress-default-backend
  namespace: default
  resourceVersion: "235953"
  selfLink: /api/v1/namespaces/default/services/nginx-ingress-default-backend
  uid: cf8f28f4-e28d-11e8-92cc-42010a840158
spec:
  clusterIP: 10.0.7.74
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-ingress
    component: default-backend
    release: nginx-ingress
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
