steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'mkdir ~/.config ; mkdir ~/.config/gcloud ; gcloud secrets versions access latest --secret=cloudbuild-sa > ~/.config/gcloud/application_default_credentials.json' ]
- name: 'gcr.io/$PROJECT_ID/packer'
  args:
  - build
  - -debug
  - -var
  - project_id=$PROJECT_ID
  - packer.json
tags: ['cloud-builders-community']
